import { useState, FormEvent, ChangeEvent } from 'react';
import './App.css';
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";



const BASE_URL = "http://localhost:8000";

interface TravelPlanResponse {
  answer: string;
}

function App() {
  const [userInput, setUserInput] = useState<string>('');
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [travelPlan, setTravelPlan] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    if (!userInput.trim()) return;

    setIsLoading(true);
    setError(null);
    setTravelPlan(null);

    try {
      const response = await fetch(`${BASE_URL}/query`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ query: userInput }),
      });

      if (response.ok) {
        const data: TravelPlanResponse = await response.json();
        const answer = data.answer || "No answer returned.";
        setTravelPlan(answer);
        setUserInput('');
      } else {
        const errorText = await response.text();
        setError(`Bot failed to respond: ${errorText}`);
      }
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Unknown error occurred';
      setError(`The response failed due to ${errorMessage}`);
    } finally {
      setIsLoading(false);
    }
  };

  const handleInputChange = (e: ChangeEvent<HTMLInputElement>) => {
    setUserInput(e.target.value);
  };

  const getCurrentDateTime = (): string => {
    const now = new Date();
    return now.toLocaleString('en-US', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      hour12: false
    });
  };

  return (
    <div className="app-container">
      <header className="app-header">
        <h1>Travel Planner Agentic Application</h1>
      </header>

      <main className="main-content">
        <div className="chat-section">
          <h2>How can I help you in planning a trip? Let me know where do you want to visit.</h2>

          <form onSubmit={handleSubmit} className="query-form">
            <input
              type="text"
              value={userInput}
              onChange={handleInputChange}
              placeholder="e.g. Plan a trip to Goa for 5 days"
              className="user-input"
              disabled={isLoading}
            />
            <button
              type="submit"
              className="submit-button"
              disabled={isLoading || !userInput.trim()}
            >
              {isLoading ? 'Thinking...' : 'Send'}
            </button>
          </form>

          {isLoading && (
            <div className="loading-container">
              <div className="spinner"></div>
              <p>Bot is thinking...</p>
            </div>
          )}

          {error && (
            <div className="error-container">
              <p>{error}</p>
            </div>
          )}

          {travelPlan && (
            <div className="travel-plan-container">
              <div className="plan-header">
                <h1>🌍 AI Travel Plan</h1>
                <p className="generated-info">
                  <strong>Generated:</strong> {getCurrentDateTime()}
                </p>
                <p className="created-by">
                  <strong>Created by:</strong> Atriyo's Travel Agent
                </p>
              </div>

              <hr />

              <div className="plan-content markdown-content">
                <ReactMarkdown remarkPlugins={[remarkGfm]}>
                  {travelPlan}
                </ReactMarkdown>
              </div>

              <hr />

              <p className="disclaimer">
                <em>This travel plan was generated by AI. Please verify all information,
                  especially prices, operating hours, and travel requirements before your trip.</em>
              </p>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}

export default App;